### ISSUE TITLE
repo_checker: adapt for maintenance workflow

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#1634]
- [x] inherit whitelist from base project (fixed in #1633)
- [ x read repo definition from OBS and walk path elements (~partial work in #1624~; fixed in #1640 and #1656)
- [x] validate multiple repos and appropriately format results (decided against in #1656)
  - at a high level needs to loop over repos (similar to archs, but also needs to sub-loop on archs)
  - requires abstracting the state check as all that is tied to staging setup
- [x] handle maintenance_release request type (fixed in #1656)
- [x] evaluate `project_only` run for `:Update` projects and determine where to place output (fixed in #1655)

**Comment by jberry-suse** [comment]
Presumably once this is complete it will also work for devel projects.
